<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Resources\guess_io_multi.ico</ApplicationIcon>
        <LangVersion>default</LangVersion>
        <AssemblyName>GuessIO</AssemblyName>
        <RootNamespace>org.russkyc.guessio</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="Russkyc.AttachedUtilities.FilestreamExtensions" Version="1.1.1" />
        <PackageReference Include="Russkyc.ModernControls.WPF" Version="1.5.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="GuessWords.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\guess_io_multi.ico" />
      <Resource Include="Resources\guess_io_multi.ico" />
    </ItemGroup>

</Project>

